### ISSUE TITLE
What is theme used in the demo?

### ISSUE THREAD

**Issue by felipevolpone** [shagabutdinov/sublime-method#4]
Hey @shagabutdinov, really nice plugin. Thanks for that. Could you tell me what is the theme that you're using in the demo at README?

thanks

**Comment by shagabutdinov** [comment]
Thank you! It is devastate-mini (https://github.com/shagabutdinov/sublime-devastate-mini) with lyte color scheme (https://packagecontrol.io/packages/Theme%20-%20Lyte)
